Add tolerance parameter for PlanarSurface and IsClosed Check
BHoM/Revit_Toolkit pull request #1082
Opened 2021-09-15 04:15 UTC by enarhi

### Issues addressed by this PR

Closes #1062 

Allows for tolerance set in RevitSettings to be applied to Planar Surface creation, thereby allowing pulling closed regions such as a FilledRegion where the region is closed per Revit tolerances, but not per default BHoM tolerances.

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231062-PlanarSurfaceTolerance?csf=1&web=1&e=kDTc7h

Test by checking with the different tolerances to confirm pull failure when tolerance value is too low, and success when tolerance is higher.

2021-09-15 04:26 UTC, enarhi commented
@BHoMBot check compliance
@BHoMBot check versioning
@BHoMBot check null-handling

2021-09-15 04:31 UTC, enarhi commented
@BHoMBot check compliance

2021-09-15 04:40 UTC, enarhi commented
@BHoMBot check required

2021-09-15 15:28 UTC, pawelbaran requested changes
As usual, the issues related to tolerances and chains of messages turn to be trickier than they are! 🙈 I have found a few minor things that could be tweaked in your code (please see the comments), plus raised https://github.com/BHoM/BHoM_Engine/pull/2622 to avoid meaningless warnings to show up (see your example with too strict tolerance).

On top of that, could you please be so kind and provide a test case for `AnalyticalOutlines` query? Thanks!

2021-09-15 15:28 UTC, pawelbaran commented on Revit_Core_Engine/Convert/Revit/FromRevit/DraftingInstance.cs
> +            List<PlanarSurface> surfaces = BH.Engine.Geometry.Create.PlanarSurface(curves, settings.DistanceTolerance);
Before line 69,  could you please add a check if (surfaces.Count == 0) and if so, then raise a warning and set the instance's location to `null`? It seems to make more sense than returning the location equal to an empty `PolySurface`. Or am I confusing things?

2021-09-15 17:31 UTC, enarhi commented
Added all changes per your comments @pawelbaran , please rereview.

2021-09-15 17:31 UTC, enarhi commented
@BHoMBot check compliance

2021-09-15 17:44 UTC, enarhi commented
@BHoMBot check versioning
@BHoMBot check null-handling

2021-09-15 23:38 UTC, enarhi commented
@pawelbaran the test files have been updated to include the case for AnalyticalOutlines, which previously failed when pulling things such as floors where the small gap issue occurs. It seems to happen most often for consecutive joining arcs along a CurveLoop, for all that's worth.

2021-09-16 11:01 UTC, pawelbaran approved these changes
All LGTM now 👍

2021-09-16 11:01 UTC, pawelbaran commented
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

2021-09-16 12:26 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2021-09-16 12:38 UTC, merged