Add method for creating solid objects from list of boundaries and filled regions.
BHoM/Revit_Toolkit pull request #1122
Opened 2021-11-10 15:25 UTC by michal-pekacki

### Issues addressed by this PR

Closes #1121

Add method for creating solid extrusion from `IList<CurveLoop>` and `Filled Region` with bottom and top limitation.

### Test files

### Changelog

### Additional comments

2021-11-10 18:48 UTC, pawelbaran requested changes
I really like the overall idea. However, I think there would be an issue with units meters vs feet - please see the comments. Besides that all good!

2021-11-10 18:48 UTC, pawelbaran commented on Revit_Core_Engine/Create/Solid.cs
> +            Document doc = filledRegion.Document;
`doc` is redundant here from what I can see

2021-11-10 18:48 UTC, pawelbaran commented on Revit_Core_Engine/Create/Solid.cs
> +            double height = topElevation - bottomElevation;
Something tells me that `topElevation` and `bottomElevation` should be converted `FromSI` before being used to call Revit API methods - please remember that the standard unit system used by BHoM is meters, not Revit-beloved feet, knees and ankles 😉

2021-11-10 18:48 UTC, pawelbaran commented on Revit_Core_Engine/Create/Solid.cs
> +                solid = solid2;
Not a mistake, but I think overwriting the variable in one line would be cleaner here
```suggestion
                solid  = SolidUtils.CreateTransformed(solid, transform);
```

2021-11-10 18:48 UTC, pawelbaran commented
@BHoMBot check compliance
@BHoMBot check null-handling

2021-11-10 18:59 UTC, pawelbaran requested changes
Two more minor changes pls

2021-11-10 18:59 UTC, pawelbaran commented on Revit_Core_Engine/Create/Solid.cs
> +        public static Solid Solid(this FilledRegion filledRegion, double bottomElevation, double topElevation)
I think the general approach is not to use `this` keyword in `Create` methods - these methods should remind factory pattern.
```suggestion
        public static Solid Solid(FilledRegion filledRegion, double bottomElevation, double topElevation)
```

2021-11-10 18:59 UTC, pawelbaran commented on Revit_Core_Engine/Create/Solid.cs
> +        public static Solid Solid(this IList<CurveLoop> boundaries, double bottomElevation, double topElevation)
...and same as above
```suggestion
        public static Solid Solid(IList<CurveLoop> boundaries, double bottomElevation, double topElevation)
```

2021-11-15 10:04 UTC, pawelbaran commented
@BHoMBot check compliance
@BHoMBot check null-handling

2021-11-15 10:17 UTC, pawelbaran commented
The code looks good, but you still need to add the copyright to the file as well as fix project compliance (each BHoM assembly reference in the .csproj file needs to have `Private` and `SpecificVersion` attributes set to `false`.

2021-11-15 13:08 UTC, michal-pekacki commented
@BHoMBot fix project file ref. 4210047549

2021-11-15 13:11 UTC, michal-pekacki commented
@BHoMBot check compliance

2021-11-16 15:17 UTC, pawelbaran commented
@BHoMBot check null-handling

2021-11-16 16:09 UTC, pawelbaran approved these changes
LGTM

2021-11-16 16:09 UTC, pawelbaran commented
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

2021-11-19 14:24 UTC, IsakNaslundBh commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4211967657

2021-11-19 14:26 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2021-11-22 10:46 UTC, merged