Add method to query closest element from another element
BHoM/Revit_Toolkit pull request #1124
Opened 2021-11-17 10:51 UTC by tiagogrossi

### Issues addressed by this PR

Closes #1123 

Adds a method to query the closest element from another element, with the ability to filter by category and distance search radius.

### Test files
N/A

### Changelog
Added `Core.Query.ClosestElement`
Added `Core.Query.HasLocation`

2021-11-17 10:51 UTC, tiagogrossi commented
@BHoMBot check compliance

2021-11-17 12:35 UTC, tiagogrossi commented
@BHoMBot check compliance

2021-11-17 12:40 UTC, tiagogrossi commented
@BHoMBot check project-compliance

2021-11-17 15:26 UTC, pawelbaran commented
@BHoMBot check compliance
@BHoMBot check null-handling

2021-11-17 16:15 UTC, pawelbaran requested changes
The general concept makes sense, but I think I have spotted a few minor issues plus proposed a few tweaks.

2021-11-25 09:38 UTC, tiagogrossi commented on Revit_Core_Engine/Query/ClosestElement.cs
> +                            XYZ searchedPoint = (searchedLocation as LocationPoint).Point;
Nicely spotted, I hadn't think of that because it's not common but it may occur sometimes. I've added the fixes

2021-11-25 16:27 UTC, pawelbaran requested changes
Just one more thing I have spotted (will be caught by check null-handling anyways)

2021-11-25 16:27 UTC, pawelbaran commented on Revit_Core_Engine/Query/ClosestElement.cs
> +        {
It would be worth to add null check for `document` and `originalElement` here I think.

2021-11-25 17:02 UTC, pawelbaran requested changes

2021-11-25 17:02 UTC, pawelbaran commented on Revit_Core_Engine/Query/ClosestElement.cs
> +                    transform = doc.LinkTransform();
Sorry I have one more comment: to make the code a bit cleaner and avoid the link being host document, you could make the following change:
```suggestion
                if(doc != document)
                    transform = doc.LinkTransform();
```

2021-12-02 13:28 UTC, closed without merging