Revit_Core_Engine: Add Color convert
BHoM/Revit_Toolkit pull request #1185
Opened 2022-04-05 14:27 UTC by tiagogrossi

### Issues addressed by this PR

Closes #1184 

Color convert added, from System.Drawing to Revit API and vice-versa.

### Test files
N/A

### Changelog
Added `BH.Revit.Engine.Core.Convert.Color.ToRevit`
Added `BH.Revit.Engine.Core.Convert.Color.FromRevit`

2022-04-05 14:28 UTC, tiagogrossi commented
@BHoMBot check compliance

2022-04-05 17:32 UTC, pawelbaran requested changes
I have no clue how did that happen that it has not been added yet - I am pretty sure that I spread a few instances of such convert across the repo, doing the convert manually each time 🙈 nice improvement. I would slightly tweak the descriptions and we are good to go!

2022-04-05 17:32 UTC, pawelbaran commented on Revit_Core_Engine/Convert/Revit/FromRevit/Color.cs
> +        [Input("color","The color to be converted")]
```suggestion
        [Input("color","Revit color to be converted.")]
```

2022-04-05 17:32 UTC, pawelbaran commented on Revit_Core_Engine/Convert/Revit/ToRevit/Color.cs
> +        [Input("color","The color to be converted")]
```suggestion
        [Input("color","System color to be converted.")]
```

2022-04-08 18:03 UTC, pawelbaran submitted a review, later dismissed
Dots' lives saved - happy to approve now!

2022-04-08 18:03 UTC, pawelbaran commented
@BHoMBot check required

2022-04-11 08:14 UTC, pawelbaran commented
@BHoMBot check compliance
@BHoMBot check null-handling

2022-04-11 08:23 UTC, pawelbaran commented
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

2022-04-11 10:03 UTC, pawelbaran approved these changes
Only minor tweak made since the last approval, re-approving now.

2022-04-11 10:43 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5968602936

2022-04-11 11:01 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2022-04-11 11:05 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2022-04-11 11:32 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2022-04-11 12:01 UTC, pawelbaran commented
@BHoMBot check core

2022-04-11 12:01 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2022-04-11 16:45 UTC, pawelbaran commented
I am closing this PR and replacing it with the rebased version under https://github.com/BHoM/Revit_Toolkit/pull/1185

2022-04-11 16:45 UTC, closed without merging