Change SetInsulation return type to bool
BHoM/Revit_Toolkit pull request #1192
Opened 2022-04-11 13:02 UTC by michal-pekacki

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1191 

Changing `SetInsulation` return type from `void` to `bool` to have better control when used other methods.

### Test files

### Changelog

### Additional comments

2022-04-11 13:02 UTC, michal-pekacki commented
@BHoMBot check compliance

2022-04-11 19:42 UTC, pawelbaran requested changes
By the looks of code, there is only one `true` returned when the insulation is deleted - what about the case when it is added/updated?

2022-04-12 08:42 UTC, michal-pekacki commented
@pawelbaran I changed the concept and find it more useful to return the newly created `InsulationLiningBase` element or `null` for invalid execution.

2022-04-12 13:38 UTC, pawelbaran approved these changes
Nonharmful, definitely improving refactoring - happy to merge as soon as the checks pass 👍

2022-04-12 13:38 UTC, pawelbaran commented
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check core

2022-04-12 13:57 UTC, pawelbaran commented
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

2022-04-12 14:42 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2022-04-12 15:46 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5992584194

2022-04-12 17:49 UTC, merged