Revit_Core_Engine: Handle secondary exception when pulling curved Revit walls
BHoM/Revit_Toolkit pull request #1211
Opened 2022-06-17 09:33 UTC by vietle-bh

### Issues addressed by this PR

Closes #1210 

On pulling a curved Revit wall, the first error is recorded right but that doesn't block a second error message due to `faces` being null.

![image](https://user-images.githubusercontent.com/102604891/174267044-a1891f0b-b6a8-4699-bcee-91bdedb8d7c5.png)

![image](https://user-images.githubusercontent.com/102604891/174267205-5f779ac6-7eb9-41d0-87b7-d074a1110ec0.png)

### Test files

[Revit file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/Revit_Toolkit/Pull/PullRepresentations.rvt?csf=1&web=1&e=5Bi3aQ)
[Gh file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/Revit_Toolkit/Pull/PullRepresentations.gh?csf=1&web=1&e=Bt0tJI)

### Changelog

- Handle secondary exception when pulling curved Revit walls.

2022-06-17 10:24 UTC, vietle-bh commented
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot ready-to-merge

2022-06-20 15:47 UTC, pawelbaran requested changes

2022-06-20 15:53 UTC, vietle-bh commented on Revit_Core_Engine/Query/PanelSurfaces.cs
> +            List<PlanarFace> planarFaces = faces?.Where(x => x is PlanarFace).Cast<PlanarFace>().ToList();
Thanks. I've made the change now.

2022-06-20 16:27 UTC, vietle-bh commented
@BHoMBot check required
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

2022-06-21 11:16 UTC, pawelbaran approved these changes
Good change, improves the robustness of the solution, happy to approve

2022-06-21 11:17 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2022-06-21 13:29 UTC, merged