Duct Elements Create Method Modified to Consider Disciplines
BHoM/Revit_Toolkit pull request #1260
Opened 2022-09-23 17:52 UTC by travispotterBH

I did not know the best place for this PR, or what was the best name of the branch, so I am prepared to remake this after comments.

### Issues addressed by this PR

Closes #1214 
Closes https://github.com/BHoM/BHoM/issues/1403

Attempts to address issue of duct objects being converted from Revit only as their analytical representation, which splits the ducts on all connected connectors (mostly only an issue on ducts with tap style fittings)

Try to Push to JSON a selected duct run with runs connected by taps and elbows like below: 
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/96432552/192026059-509d1882-8c4d-4a83-b99f-ee8b58add97a.png)

export the same duct run as a physical discipline and as an environmental discipline. 

On the case of runs with tap fittings:
Physical Discipline should export just as the single, not separated by midpoint, Revit Element.
Environmental Discipline should export as the separated by midpoint element and should have multiple bhomobjects of type Duct of the same Revit Element Id. 

Runs without tap fittings should export similar to the Physical discipline would. 

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/96432552/192026053-f01c4595-6c84-40cc-8689-d9c547dacaa3.png)

This was achieved by changing the `FromRevit` `Convert` Method for ducts called `DuctFromRevit` to take in the discipline provided, and that is passed into the `Query.LocationCurveMEP` method which then will either split or not split the duct line based on the discipline given. 

This method of doing this required edits to the `FromRevit` Convert method that handles `Element` types where it was required the new Invocation of the `convertMethod` would be able to handle additional parameters, namely the `Discipline` type. This further required a change to `Query.AllConvertMethods` to check for methods that have between three and four parameters instead of what was previous set to three.

@pawelbaran I recognize that this may not be the most optimal solution, and I welcome your comments/suggestions/assistance.

@kayleighhoude can you give some indication on how well this suits your needs. 

### Test files

Revit file: Any revit file with some ducts and fittings connected in a duct run
Expected Results:

### Changelog

### Additional comments

2022-09-26 09:32 UTC, pawelbaran requested changes
I am afraid you are jumping too far ahead with this PR @travispotterBH. The current system around the Revit converts is based on the concept of having one convert per object type. This means you cannot have 2 types of converts to MEP ducts depending on discipline input (see the code comments).

Instead, you would need to start from adding MEP objects to the `Physical` namespace (Physical_oM) to then start supporting them in Revit_Toolkit. I hope this makes sense - even if taking a shortcut sounds tempting in short term, I am pretty sure we would need to pay double price once we realise the amount of extra effort required to make it work plus potentially refactor in long term.

2022-09-26 09:32 UTC, pawelbaran commented on Revit_Core_Engine/Convert/MEP/FromRevit/Duct.cs
> +        public static List<BH.oM.MEP.System.Duct> DuctFromRevit(this Autodesk.Revit.DB.Mechanical.Duct revitDuct, RevitSettings settings = null, Dictionary<string, List<IBHoMObject>> refObjects = nul
`Discipline` method parameter should not be added to this method - if you need it, please make this method `private` and then expose it via one-line public converts for physical and MEP disciplines that would call it.

2022-09-26 09:32 UTC, pawelbaran commented on Revit_Core_Engine/Query/LocationCurve.cs
> +        public static List<BH.oM.Geometry.Line> LocationCurveMEP(this MEPCurve mepCurve, RevitSettings settings = null, Discipline discipline = Discipline.Physical)
This is fine, there is no limitations on the `Query` methods.

2023-01-03 18:25 UTC, travispotterBH commented
Will not planned to be resolved in this sprint.

2023-01-03 18:25 UTC, closed without merging