Add method for converting MeshElement from revit
BHoM/Revit_Toolkit pull request #1275
Opened 2022-11-16 13:22 UTC by IsakNaslundBh

### Issues addressed by this PR

Adds method for converting any element to MeshElement from Revit

### Test files

### Changelog

### Additional comments

2022-11-17 15:46 UTC, pawelbaran requested changes

2022-11-17 15:46 UTC, pawelbaran commented on Revit_Core_Engine/Convert/Physical/FromRevit/MeshElement.cs
> +            Options meshOptions = Create.Options(ViewDetailLevel.Medium, true, true);
Not entirely sure about including invisible geometries, but my gut feeling is that it should be `false`, assuming that physical namespace represents only the visible aspects of objects. On the other hand, I am 100% sure you do not need to compute references. So finally I would consider changing the code as follows:

```suggestion
            Options meshOptions = Create.Options(ViewDetailLevel.Medium, false, false);
```

2022-11-23 22:11 UTC, pawelbaran submitted a review, later dismissed
Approving this PR without extensive testing on the basis of the code to be fully validated as a part of the wider workflow developed by @IsakNaslundBh

2022-11-25 16:32 UTC, pawelbaran submitted a review, later dismissed
Approving the latest tweak that fixes diffing - however, could you please update the title @IsakNaslundBh?

2023-01-09 13:39 UTC, pawelbaran approved these changes
This PR looks good now I believe - happy to approve and continue the review on other threads.

2023-01-09 17:42 UTC, FraserGreenroyd requested changes

2023-01-09 17:42 UTC, FraserGreenroyd commented on Revit_Core_Engine/Convert/Physical/FromRevit/MeshElement.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-01-10 10:54 UTC, pawelbaran submitted a review, later dismissed
Approving on the basis of the previous review.

2023-01-10 10:54 UTC, pawelbaran commented
@BHoMBot check compliance
@BHoMBot check core

2023-01-10 10:56 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-01-10 12:11 UTC, pawelbaran submitted a review, later dismissed
Approving on the basis of the previous review.

2023-01-11 13:44 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-01-12 17:24 UTC, pawelbaran approved these changes
Approving on the basis of previous reviews

2023-01-13 10:53 UTC, pawelbaran commented
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check installer

2023-01-13 11:47 UTC, FraserGreenroyd commented
@BHoMBot check installer

2023-01-13 12:25 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-01-13 12:26 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10628311344

2023-01-13 12:28 UTC, merged