Revit_Engine: fix the copy of the DiffingConfig properties
BHoM/Revit_Toolkit pull request #1334
Opened 2023-03-28 16:50 UTC by alelom

### Issues addressed by this PR

Closes #1333

### Test files

Run the tests in DiffingTests prototypes. All must pass. The relevant ones are the ones linked in https://github.com/BHoM/DiffingTests_Prototypes/issues/10: `PropertyNumericTolerances_Equal` and `PropertyNumericTolerances_Different`.

### Changelog

### Additional comments

2023-03-28 17:38 UTC, FraserGreenroyd commented
@alelom could we not include the DiffingTests as part of unit tests on this repo then if they're linked to Revit_Toolkit diffing operations?

2023-03-29 08:55 UTC, alelom commented
> > > @alelom could we not include the DiffingTests as part of unit tests on this repo then if they're linked to Revit_Toolkit diffing operations?
> > 
> > 
> > Diffing Tests includes a dedicated revitdiffing project, which is why it is referenced as part of this pr. As per why they are there rather than here: I considered to move them in the the Revit toolkit (you probably remember me mentioning that). However, when you look at the diffing behaviour on the Revit side, there are places (most places) where it is incredibly helpful to step into the code that belongs to the base Diffing engine. Not to go off topic, anyways I think that we could find ways to separate them more, adding a Revit unit test project here, but I think that some "integration tests" would still be needed and would need to sit in an overarching toolkit like the diffingtests prototypes. I have been thinking about solutions to formalise this more, happy to workshop something together.
> 
> Makes sense - though I think longterm we should look to add DiffingTests to the BHoM_Engine at the very least, just so we can perform automated tests on PRs and a nightly basis via the bot to protect the diffing parts? But happy to discuss away from this PR - your reasoning for the above makes sense to me 👍

Definitely agree!

2023-04-03 09:03 UTC, pawelbaran requested changes
I have gone through the code and have left only one minor comment. However, 2 diffing tests do not pass on my build:

![image](https://user-images.githubusercontent.com/26874773/229463275-10042e51-e9a6-40c6-97c6-5c3d68564918.png)

![image](https://user-images.githubusercontent.com/26874773/229463291-d4004c26-e0f8-4935-a04a-6cf4c86a88a6.png)

2023-04-06 09:27 UTC, alelom commented on Revit_Engine/Compute/RevitDiffing.cs
>                  if (diffConfig != null)
No this is still needed, in case an user invokes the `RevitDiffing` method (the overload at line 114) and passes in a `null` diffingConfig.

2023-04-06 09:37 UTC, pawelbaran commented on Revit_Engine/Compute/RevitDiffing.cs
>                  if (diffConfig != null)
But isn't `diffConfig` going to always be assigned after the addition you made in line 147?

![image](https://user-images.githubusercontent.com/26874773/230337636-0dd7bdd9-1daa-4339-8043-61edf428f4ea.png)

2023-04-06 09:51 UTC, alelom commented on Revit_Engine/Compute/RevitDiffing.cs
>                  if (diffConfig != null)
Actually yes you're right! :)

2023-04-06 09:53 UTC, alelom commented on Revit_Engine/Compute/RevitDiffing.cs
>                  if (diffConfig != null)
Removed in https://github.com/BHoM/Revit_Toolkit/pull/1334/commits/18b371ea96246fd798d5cc5a3b436db53e6de349

2023-04-06 13:59 UTC, alelom commented
> I have gone through the code and have left only one minor comment. However, 2 diffing tests do not pass on my build:

Just for the record, this was due to an issue in DiffingTests_Prototypes which has now been solved: https://github.com/BHoM/DiffingTests_Prototypes/issues/9

2023-04-12 17:53 UTC, pawelbaran commented
@BHoMBot check core
@BHoMBot check compliance

2023-04-12 18:00 UTC, pawelbaran commented
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

2023-04-12 18:07 UTC, pawelbaran approved these changes
All tests have passed, more testing done on Revit diffing with satisfying results.

2023-04-12 18:08 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2023-04-13 07:55 UTC, merged