Documentation compliance issues
BHoM/Revit_Toolkit pull request #1339
Opened 2023-03-31 15:32 UTC by travispotterBH

### NOTE: Depends on 

### Issues addressed by this PR

Closes #1331 

### Test files

### Changelog

- Compliance issues addressed.

### Additional comments

2023-03-31 15:33 UTC, travispotterBH commented
Hey @BHoMBot check documentation-compliance for me please. I've made a few changes, and want to easily see what is left to resolve. Thanks 😄

2023-03-31 16:03 UTC, travispotterBH commented
Hey @BHoMBot check documentation-compliance for me please. I've made a few changes, and want to easily see what is left to resolve. Thanks 😄

2023-03-31 16:07 UTC, travispotterBH commented
@pawelbaran please check for correctness of changes to inputs, descriptions, and in particular please review the addition of `throw NotImplementedException` on these methods below:
https://github.com/BHoM/Revit_Toolkit/blob/26d45c5ffba16e962551813306ca0f12a1c9033e/Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs#L115-L118

2023-04-01 13:56 UTC, travispotterBH commented
@BHoMBot  would you be so kind as to check required?

2023-04-03 16:23 UTC, travispotterBH commented
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

2023-04-03 21:58 UTC, pawelbaran requested changes

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Adapter/Listener/Forms/UpdatePortsForm.cs
> +        [Description("Window for updating ports used in the Revit Listener.")]
```suggestion
        [Description("Constructor of window for updating ports used by the Revit Listener.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Adapter/RevitListenerAdapter.cs
> +        [Description("Revit listener adapter constructor.")]
```suggestion
        
        [Description("Revit listener adapter constructor.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method returning RenderNodeAction to be taken at the start of parsing an ElementNode.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method to be executed at the end of parsing an ElementNode.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +            throw new NotImplementedException();
This method is empty on purpose: it says 'do nothing if you get here', which is very different from 'throw an exception if you get here' 😉 so please bring it back to the original state - refers to all cases where you have added the exception.

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method returning RenderNodeAction to be taken against an edge of a face.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method returning RenderNodeAction to be taken against a face silhouette.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method returning RenderNodeAction to be taken against a curve.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method returning RenderNodeAction to be taken against a polyline.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method to be executed against a line segment.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method to be executed against a polyline segment.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
> +        [Description("Method used to return a RenderNodeAction.")]
```suggestion
        [Description("Method to be executed against a text.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Objects/WarningSwallower.cs
> +        [Description("Failure message swallower, used to continue the process without regard to errors.")]
Your text should be the description of a class itself.

Here I would put something along the lines:
```suggestion
        
        [Description("Preprocess the failures, in this case swallow all of them.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Query/ElementType.cs
> +        settings = null) {
I am not a big fan of splitting method parameters into separate lines, and I am even less of a fan of putting the entry bracket at the end of preceding line (maybe this is why I have never learnt js 🙈)

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Query/RenderMeshes.cs
> +        [Output("renderMeshes", "RenderMesh objects corresponding to the input Revit Element.")]
```suggestion
        [Output("renderMeshes", "RenderMesh objects representing the input Revit Element.")]
```

2023-04-03 21:58 UTC, pawelbaran commented on Revit_Core_Engine/Query/RenderMeshes.cs
>          [Input("element", "Element to display thorugh RenderMeshes.")]
```suggestion
        [Input("element", "Element to display through RenderMeshes.")]
```

2023-04-03 22:59 UTC, travispotterBH commented
@BHoMBot  check required

2023-04-04 00:09 UTC, travispotterBH commented
@bhombot check copyright-compliance
@BHoMBot  check dataset-compliance

2023-04-04 09:10 UTC, pawelbaran approved these changes
Happy with the changes now 👍

2023-04-04 09:18 UTC, merged