Add new methods to Revit_Core_Engine
BHoM/Revit_Toolkit pull request #1344
Opened 2023-04-05 12:00 UTC by vietle-bh

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1343 

Added new methods such as:
- Get the intersection points of 2 vectors
- Get the smallest possible angle between 2 vectors
- Get the closest point from a point cloud
- Check if a line or face is vertical

### Test files

### Changelog

### Additional comments

2023-04-14 16:05 UTC, pawelbaran requested changes
The code does not compile...

Also I do not think you need the geometry methods, taken we have all of them in Geometry_Engine.

2023-05-24 10:17 UTC, michal-pekacki commented on Revit_Core_Engine/Query/LocationPoint.cs
> +        public static XYZ LocationPoint(this Element elem, bool useCurveMidPoint = false)
I used this in Revit_Tools:
https://github.com/BuroHappoldEngineering/Revit_Tools/blob/46ea8bd0477f281468fc7cab79ef6adcf17fb580/Revit_Mechanical_Engine/Compute/ReferenceLevel.cs#L203-L229

2023-05-24 13:30 UTC, vietle-bh commented on Revit_Core_Engine/Query/LocationPoint.cs
> +        public static XYZ LocationPoint(this Element elem, bool useCurveMidPoint = false)
Michal's method can indeed do the same thing. I'll move it here.

2023-05-24 14:23 UTC, vietle-bh commented on Revit_Core_Engine/Compute/VectorIntersection.cs
> +        public static XYZ VectorIntersection(this XYZ startPoint, XYZ endPoint, XYZ startDir, XYZ endDir)
If I replaced this with LineIntersection, this:
`XYZ elbowPnt = Core.Compute.VectorIntersection(startPoint, endPoint, startDir, endDir);`

will turn into:

```c#
var line1 = new BhLine { Start = startPoint.PointFromRevit(), End = (startPoint + startDir).PointFromRevit() };
var line2 = new BhLine { Start = endPoint.PointFromRevit(), End = (endPoint + endDir).PointFromRevit() };

line1.Infinite = true;
line2.Infinite = true;

XYZ elbowPnt = line1.LineIntersection(line2, true).ToRevit();
```

Is it worth it?

2023-05-24 15:57 UTC, pawelbaran commented on Revit_Core_Engine/Compute/VectorIntersection.cs
> +        public static XYZ VectorIntersection(this XYZ startPoint, XYZ endPoint, XYZ startDir, XYZ endDir)
I think so, but I would first ask if you will still need it if all geometry/maths will be done on the BHoM side, not on Revit?

2023-05-24 15:59 UTC, vietle-bh commented on Revit_Core_Engine/Compute/VectorIntersection.cs
> +        public static XYZ VectorIntersection(this XYZ startPoint, XYZ endPoint, XYZ startDir, XYZ endDir)
Sure, I'll change to using the longer form.
The example above is in Revit_Toolkit where my new methods purely deal with Revit objects.

2023-05-24 16:00 UTC, vietle-bh commented on Revit_Core_Engine/Compute/VectorIntersection.cs
> +        public static XYZ VectorIntersection(this XYZ startPoint, XYZ endPoint, XYZ startDir, XYZ endDir)
So geometry/math calls are on the Revit side.

2023-05-26 08:24 UTC, vietle-bh commented
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

2023-06-23 11:08 UTC, vietle-bh commented
Closing to reopen this PR because the commit history has rewritten itself.

2023-06-23 11:08 UTC, closed without merging