ConnectedElements - duplicate elements bugfix
BHoM/Revit_Toolkit pull request #1475
Opened 2024-04-17 13:33 UTC by michal-pekacki

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #

Fixed duplicated elements bug.

### Test files

### Changelog

### Additional comments

2024-04-22 10:24 UTC, pawelbaran requested changes

2024-04-22 10:24 UTC, pawelbaran commented on Revit_Core_Engine/Query/ConnectedElements.cs
> +            List<Element> connectedElements = new List<Element>();
You can make the method look more neat by using `HashSet<ElementId>`

```suggestion
            HashSet<ElementId> connectedElements = new HashSet<ElementId>();
```

...then:
```C#
(...)
 if (el != null && el.Id != element.Id)
    connectedElements.Add(el.Id);
```

2024-04-22 10:24 UTC, pawelbaran commented on Revit_Core_Engine/Query/ConnectedElements.cs
> +            return connectedElements;
```suggestion
            return connectedElements.ToList();
```

2024-04-22 10:24 UTC, pawelbaran commented on Revit_Core_Engine/Query/Connectors.cs
> +        /***************************************************/
Private methods header is missing 😉

2024-04-22 10:24 UTC, pawelbaran commented on Revit_Core_Engine/Query/Connectors.cs
> +        [Output("cconnectors", "MEP Element connectors.")]
```suggestion
        [Output("connectors", "MEP Element connectors.")]
```

2024-04-22 10:24 UTC, pawelbaran commented on Revit_Core_Engine/Query/Connectors.cs
> +            foreach (Connector conn in connSet)
What if `connSet == null`?

2024-04-22 10:24 UTC, pawelbaran commented on Revit_Core_Engine/Query/Connectors.cs
> +            foreach (Connector conn in connSet)
What if `connSet == null`?

2024-04-22 10:24 UTC, pawelbaran commented on Revit_Core_Engine/Query/Connectors.cs
> +            BH.Engine.Base.Compute.RecordError("Input element is not supported by the method. Check if element is a valid MEP object.");
```suggestion
            BH.Engine.Base.Compute.RecordError("Input element is not supported by the connector query method. Check if element is a valid MEP object.");
```

2024-04-22 12:45 UTC, michal-pekacki commented on Revit_Core_Engine/Query/Connectors.cs
> +            foreach (Connector conn in connSet)
Null check added 👍

2024-04-22 15:13 UTC, michal-pekacki commented
@BHoMBot check compliance

2024-04-23 09:40 UTC, pawelbaran approved these changes
Happy to approve, changes make sense and work based on the review session with @michal-pekacki 👍

2024-04-23 11:58 UTC, michal-pekacki commented
@BHoMBot check required

2024-04-23 12:53 UTC, michal-pekacki commented
@BHoMBot check ready-to-merge

2024-05-09 09:46 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2024-05-09 09:52 UTC, merged